# Generated by Django 4.2.2 on 2024-07-11 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="habit",
            old_name="user",
            new_name="owner",
        ),
    ]
