# Generated by Django 4.2.2 on 2024-07-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_rename_user_habit_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="periodicity",
            field=models.SmallIntegerField(
                default=1,
                help_text="Укажите периодичность от 1 до 7, где 1 - один раз в неделю, а 7 - это каждый день",
                verbose_name="Периодичность выполнения привычки",
            ),
        ),
    ]
