# Generated by Django 4.2.2 on 2024-07-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_alter_habit_periodicity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="periodicity",
            field=models.SmallIntegerField(
                default=1,
                help_text="Укажите периодичность от 1 до 7, где 1 - один раз в неделю, а 7 - это каждый день.",
                verbose_name="Периодичность выполнения привычки",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.DateTimeField(
                help_text="Укажите дату и время выполнения привычки",
                verbose_name="Дата и время страта выполнения привычки",
            ),
        ),
    ]
